<?php

return [
    'actions' => ['view' => 'Lihat', 'create' => 'Tambah', 'update' => 'Ubah', 'delete' => 'Hapus'],
    'modules' => [
        'dashboard' => ['route' => 'home', 'label' => 'Dashboard (ringkasan lintas modul)', 'actions' => ['view']],
        'pengguna' => ['route' => 'pengguna.index', 'label' => 'Pengguna / Pelamar', 'actions' => ['view', 'update', 'delete']],
        'lowongan' => ['route' => 'lowongan.index', 'label' => 'Lowongan', 'actions' => ['view', 'create', 'update', 'delete']],
        'lamaran' => ['route' => 'lamarans.index', 'label' => 'Lamaran', 'actions' => ['view', 'update']],
        'peralihan' => ['route' => 'peralihan.index', 'label' => 'Peralihan Pelamar', 'actions' => ['view', 'update']],
        'ptk' => ['route' => 'permintaan-tenaga-kerja.index', 'label' => 'Permintaan Tenaga Kerja', 'actions' => ['view', 'create', 'update']],
        'kandidat' => ['route' => 'kandidat-potensial.index', 'label' => 'Kandidat Potensial', 'actions' => ['view', 'update']],
        'assessment' => ['route' => 'assessment-links.index', 'label' => 'Link Asesmen dan Dokumen', 'actions' => ['view', 'create', 'update', 'delete']],
        'pkwt' => ['route' => 'pkwt-contracts.index', 'label' => 'PKWT 1', 'actions' => ['view', 'update']],
        'pkwt_settings' => ['route' => 'pkwt-contract-settings.edit', 'label' => 'Pengaturan PKWT', 'actions' => ['view', 'update']],
        'personal' => ['route' => 'personal-file.index', 'label' => 'Personal File', 'actions' => ['view']],
        'pengumuman' => ['route' => 'pengumumans.index', 'label' => 'Pengumuman', 'actions' => ['view', 'create', 'update', 'delete']],
        'email' => ['route' => 'email-blast-log.index', 'label' => 'Email Log / Blast Email HR', 'actions' => ['view', 'create']],
        'recovery' => ['route' => 'account-recovery-requests.index', 'label' => 'Request Lupa Akun Pelamar', 'actions' => ['view', 'update']],
    ],
    'controllers' => [
        'DasborController' => 'dashboard',
        'PenggunaController' => 'pengguna',
        'SyaratKetentuanController' => 'pengguna',
        'LowonganController' => 'lowongan',
        'LamaranController' => 'lamaran',
        'PeralihanPelamarController' => 'peralihan',
        'PermintaanTenagaKerjaController' => 'ptk',
        'KandidatPotensialController' => 'kandidat',
        'AssessmentLinkController' => 'assessment',
        'AssessmentDocumentController' => 'assessment',
        'PkwtContractController' => 'pkwt',
        'PkwtContractSettingController' => 'pkwt_settings',
        'PersonalController' => 'personal',
        'PengumumanController' => 'pengumuman',
        'EmailBlastController' => 'email',
        'AccountRecoveryRequestController' => 'recovery',
    ],
    // Explicit mapping: a new controller action has no access until reviewed here.
    'methods' => [
        'index' => 'view', 'show' => 'view', 'download' => 'view', 'downloadZip' => 'view',
        'lowonganData' => 'view', 'lowonganChart' => 'view', 'getLamaranData' => 'view',
        'directToLamaran' => 'view', 'adminIndex' => 'view', 'adminDownload' => 'view', 'revealPin' => 'view',
        'create' => 'create', 'store' => 'create',
        'edit' => 'update', 'update' => 'update', 'autoUpdate' => 'update',
        'updateStatusAkun' => 'update', 'updateStatusMassal' => 'update', 'importStatusLamaran' => 'update',
        'refreshDataPelamar' => 'update', 'storeCandidates' => 'update', 'deactivate' => 'update',
        'updatePin' => 'update', 'extendExpiry' => 'update', 'updateVisibility' => 'update',
        'bulkUpdateVisibility' => 'update', 'rematch' => 'update', 'retrySignatureSync' => 'update',
        'approve' => 'update', 'reject' => 'update', 'bulkAction' => 'update',
        'destroy' => 'delete', 'adminDestroy' => 'delete',
    ],
];
